param(
    [Parameter(Mandatory=$true)]
    [string]$CodeQLOutput = "",
    
    [Parameter(Mandatory=$true)]
    [string]$PackageVulnerabilities = "",
    
    [Parameter(Mandatory=$true)]
    [string]$TrivyOutput = "",
    
    [Parameter(Mandatory=$true)]
    [string]$Output = "artifacts/security-alerts.detailed.md"
)

# Create output directory if it doesn't exist
$outputDir = Split-Path -Path $Output -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Initialize the report
$report = @"
# Security Alerts Report

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Executive Summary

This report consolidates all security findings from the CI/CD pipeline including:
- CodeQL Static Analysis
- Package Vulnerability Scanning
- Container Image Scanning (Trivy)

---

## 1. CodeQL Security Analysis

"@

if ($CodeQLOutput -and (Test-Path $CodeQLOutput)) {
    $codeqlContent = Get-Content $CodeQLOutput -Raw
    $report += @"

### Status
CodeQL analysis has been completed.

### Details
\`\`\`
$codeqlContent
\`\`\`

**Action:** Review findings in the GitHub Security tab under Code Scanning alerts.

"@
} else {
    $report += @"

### Status
No CodeQL findings or analysis skipped.

"@
}

$report += @"

---

## 2. Package Vulnerability Scan

"@

if ($PackageVulnerabilities -and (Test-Path $PackageVulnerabilities)) {
    $pkgContent = Get-Content $PackageVulnerabilities -Raw
    $report += @"

### Detected Vulnerabilities
\`\`\`
$pkgContent
\`\`\`

**Severity Levels Found:**
- Critical: Immediate action required
- High: Update packages as soon as possible
- Medium: Plan updates within sprint
- Low: Consider in maintenance window

**Action:** Review the package dependencies and update vulnerable packages to patched versions.

"@
} else {
    $report += @"

### Status
No vulnerable packages detected.

"@
}

$report += @"

---

## 3. Container Image Vulnerability Scan (Trivy)

"@

if ($TrivyOutput -and (Test-Path $TrivyOutput)) {
    try {
        $trivyJson = Get-Content $TrivyOutput -Raw | ConvertFrom-Json
        $results = $trivyJson.runs[0].results
        
        if ($results) {
            $criticalCount = ($results | Where-Object { $_.level -eq "error" } | Measure-Object).Count
            $warningCount = ($results | Where-Object { $_.level -eq "warning" } | Measure-Object).Count
            
            $report += @"

### Vulnerability Summary
- **Critical Issues:** $criticalCount
- **Warnings:** $warningCount

### Top Vulnerabilities (First 20)
\`\`\`
"@
            
            $results | Select-Object -First 20 | ForEach-Object {
                $report += "$($_.message.text)`n"
            }
            
            $report += @"
\`\`\`

**Action:** Review the container base image and application dependencies for vulnerabilities. Update to patched versions.

"@
        } else {
            $report += @"

### Status
No container vulnerabilities detected in the Trivy scan.

"@
        }
    } catch {
        $report += @"

### Trivy Scan Results
\`\`\`
$TrivyOutput
\`\`\`

"@
    }
} else {
    $report += @"

### Status
Trivy scan output not available.

"@
}

$report += @"

---

## Remediation Guidance

### For CodeQL Issues
1. Review the specific code findings
2. Understand the security implications
3. Apply fixes to eliminate the vulnerability
4. Verify fixes with re-scanning

### For Package Vulnerabilities
1. Update to the latest patched version of vulnerable packages
2. Run tests to ensure compatibility
3. Review breaking changes in package updates
4. Deploy and verify in staging first

### For Container Image Issues
1. Update base image to the latest patched version
2. Rebuild the container image
3. Re-scan to verify vulnerabilities are resolved
4. Redeploy with the new image

---

## Summary

All security alerts have been consolidated in this report. Each finding requires investigation and remediation based on severity level.

For more details, visit the GitHub Security tab or check individual workflow run logs.

---

**Report Generated By:** Security Alerts Agent
**CI/CD Run:** $env:GITHUB_RUN_ID
"@

# Save the report
$report | Out-File -FilePath $Output -Encoding UTF8
Write-Host "Security alerts report generated: $Output"
